version: '3.7'

services:
  vns:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/vns/src
    expose:
      - '8080'
    ports:
      - '8080:8080'
  db:
    image: postgres:11.16
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - '5432:5432'