version: '3.7'

services:
  vns:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/vns/src
    expose:
      - '8080'
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:11.16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  